package com.example.cscb07_app.Controller;

public enum DialogId {
  CREATE_FIRST_ADMIN_DETAILS,
  CREATE_FIRST_EMPLOYEE_DETAILS,
  LOGIN_INCORRECT_CREDENTIALS,
  AGE_EMPTY_DIALOG,
  CREATE_COUPON_DIALOG,
  CREATE__NEW_USER_DETAILS,
  NULL_DIALOG,
  CHECKOUT_CART,
  SAVE_SHOPPING_CART,
  SAVED_SHOPPING_CART,
  LOAD_CART_FAILED,
  CHECKOUT_LOADED_CART
}
